Entity:
  Zombie:
    Weapon: 276
    Helmet: 310
    Chestplate: 311
    Leggings: 312
    Boots: 313
  Skeleton:
    Weapon: 261
    Helmet: 310
    Chestplate: 311
    Leggings: 312
    Boots: 313
  PigZombie:
    Weapon: 283
    Helmet: 310
    Chestplate: 311
    Leggings: 312
    Boots: 313
  WitherSkeleton:
    Weapon: 272
    Helmet: 310
    Chestplate: 311
    Leggings: 312
    Boots: 313
itemCanBeDrop: false
disabledWorlds:
- put_here_disabled_worlds